name: apms_project
description: Advance Parking Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_map: ^4.0.0
  flutter_map_marker_cluster: ^1.1.1
  latlong2: ^0.8.1
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1
  image_picker: ^1.0.2
  provider: ^6.0.5
  firebase_storage: ^11.2.6
  firebase_core: ^2.15.1
  permission_handler: ^10.4.5
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  image: "assets/images/Plogo.png"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets\images\car.json



  #run this commands for splash screen
  #flutter clean
  #flutter pub get
  #flutter pub run flutter_native_splash:create